version: "3.7"
services:

  backend:       
    container_name: python_uvicorn_fastapi_prod
    image: smascha/python-uvicorn-fastapi:production
    build:
      context: ./backend
      dockerfile: backend.dockerfile
      target: production
      args:
        POETRY_VERSION: 1.1.5
    env_file:
      - ./backend/.env
      - ./backend/.env_production
    ports:
      - "80:80"

  frontend:
    build: frontend
    depends_on:
      - backend
    volumes:
        - ./storage:/storage


#     labels:
#       - "traefik.enable=true"
#       - "traefik.http.routers.hr_api.rule=Host(`hr-api.smascha.ai`)"
#       - "traefik.http.routers.hr_api.entrypoints=websecure"
#       - "traefik.http.routers.hr_api.tls.certresolver=mytlschallenge"
#     networks:
#       - proxy
#     restart: always

# networks:
#   proxy:
#     external: true
